export const nigeriaLocations = [
  // ========== LAGOS STATE ==========
  "Lagos — Agbara",
  "Lagos — Agege",
  "Lagos — Agric",
  "Lagos — Ajah",
  "Lagos — Alaba International",
  "Lagos — Alimosho",
  "Lagos — Allen Avenue",
  "Lagos — Amuwo Odofin",
  "Lagos — Apapa",
  "Lagos — Apapa GRA",
  "Lagos — Awoyaya",
  "Lagos — Badagry",
  "Lagos — Banana Island",
  "Lagos — Bariga",
  "Lagos — Bode Thomas",
  "Lagos — Bogije",
  "Lagos — Chevron",
  "Lagos — Coker",
  "Lagos — Dolphin Estate",
  "Lagos — Egbeda",
  "Lagos — Ejigbo",
  "Lagos — Epe",
  "Lagos — Festac",
  "Lagos — Gbagada",
  "Lagos — Idimu",
  "Lagos — Ifako",
  "Lagos — Ifako-Ijaiye",
  "Lagos — Igando",
  "Lagos — Iganmu",
  "Lagos — Ijegun",
  "Lagos — Ikeja",
  "Lagos — Ikeja GRA",
  "Lagos — Ikorodu",
  "Lagos — Ikoyi",
  "Lagos — Ilaje",
  "Lagos — Ipaja",
  "Lagos — Isale Eko",
  "Lagos — Isolo",
  "Lagos — Jakande",
  "Lagos — Ketu",
  "Lagos — Kosofe",
  "Lagos — Lagos Island",
  "Lagos — Lagos Mainland",
  "Lagos — Lekki Phase 1",
  "Lagos — Lekki Phase 2",
  "Lagos — Lekki Phase 3",
  "Lagos — Magodo",
  "Lagos — Maryland",
  "Lagos — Masha",
  "Lagos — Mende",
  "Lagos — Meiran",
  "Lagos — Mile 2",
  "Lagos — Mile 12",
  "Lagos — Mushin",
  "Lagos — Obafemi Awolowo Way",
  "Lagos — Ogudu",
  "Lagos — Ojodu Berger",
  "Lagos — Ojota",
  "Lagos — Ojo",
  "Lagos — Okota",
  "Lagos — Olodi Apapa",
  "Lagos — Omole Phase 1",
  "Lagos — Omole Phase 2",
  "Lagos — Oniru",
  "Lagos — Oregun",
  "Lagos — Orile",
  "Lagos — Oshodi",
  "Lagos — Osapa London",
  "Lagos — Pencinema",
  "Lagos — Portharcourt Road",
  "Lagos — Satellite Town",
  "Lagos — Sangotedo",
  "Lagos — Shomolu",
  "Lagos — Surulere",
  "Lagos — Tejuosho",
  "Lagos — Victoria Garden City",
  "Lagos — Victoria Island",
  "Lagos — Yaba",

  // ========== FCT ABUJA ==========
  "Abuja — Apo",
  "Abuja — Asokoro",
  "Abuja — Bwari",
  "Abuja — Central Area",
  "Abuja — Dakibiyu",
  "Abuja — Dape",
  "Abuja — Dawaki",
  "Abuja — Durumi",
  "Abuja — Galadimawa",
  "Abuja — Garki",
  "Abuja — Garki 2",
  "Abuja — Gudu",
  "Abuja — Guzape",
  "Abuja — Gwagwalada",
  "Abuja — Gwarinpa",
  "Abuja — Idu Industrial",
  "Abuja — Jabi",
  "Abuja — Jahi",
  "Abuja — Kabusa",
  "Abuja — Kado",
  "Abuja — Katampe",
  "Abuja — Katampe Extension",
  "Abuja — Kaura",
  "Abuja — Kuje",
  "Abuja — Kubwa",
  "Abuja — Life Camp",
  "Abuja — Lokogoma",
  "Abuja — Lugbe",
  "Abuja — Mabushi",
  "Abuja — Maitama",
  "Abuja — Mpape",
  "Abuja — Nbora",
  "Abuja — Utako",
  "Abuja — Wuye",
  "Abuja — Wuse",
  "Abuja — Wuse 2",
  "Abuja — Nyanya",
  "Abuja — Karu",
  "Abuja — Orozo",
  "Abuja — Games Village",
  "Abuja — Three Arms Zone",

  // ========== RIVERS STATE ==========
  "Port Harcourt — Aggrey Road",
  "Port Harcourt — Abuloma",
  "Port Harcourt — Borokiri",
  "Port Harcourt — Choba",
  "Port Harcourt — D-Line",
  "Port Harcourt — Diobu",
  "Port Harcourt — Eagle Island",
  "Port Harcourt — Elekahia",
  "Port Harcourt — Forces Avenue",
  "Port Harcourt — GRA Phase 1",
  "Port Harcourt — GRA Phase 2",
  "Port Harcourt — GRA Phase 3",
  "Port Harcourt — Marine Base",
  "Port Harcourt — Mile 1",
  "Port Harcourt — Mile 2",
  "Port Harcourt — Mile 3",
  "Port Harcourt — Nkpolu",
  "Port Harcourt — Obio",
  "Port Harcourt — Ogbunabali",
  "Port Harcourt — Okporo",
  "Port Harcourt — Old GRA",
  "Port Harcourt — Ozuoba",
  "Port Harcourt — Peter Odili Road",
  "Port Harcourt — Rumuigbo",
  "Port Harcourt — Rumuodara",
  "Port Harcourt — Rumuokoro",
  "Port Harcourt — Rumuola",
  "Port Harcourt — Trans Amadi",
  "Port Harcourt — Woji",
  "Rivers — Ahoada",
  "Rivers — Bonny Island",
  "Rivers — Degema",
  "Rivers — Eleme",
  "Rivers — Gokana",
  "Rivers — Ikwerre",
  "Rivers — Okrika",
  "Rivers — Omoku",
  "Rivers — Oyigbo",
  "Rivers — Tai",

  // ========== OYO STATE ==========
  "Ibadan — Agodi",
  "Ibadan — Agodi GRA",
  "Ibadan — Akobo",
  "Ibadan — Alakia",
  "Ibadan — Apata",
  "Ibadan — Bashorun",
  "Ibadan — Bodija",
  "Ibadan — Challenge",
  "Ibadan — Eleyele",
  "Ibadan — Eruwa Road",
  "Ibadan — Felele",
  "Ibadan — GRA",
  "Ibadan — Ibadan South West",
  "Ibadan — Ikolaba",
  "Ibadan — Iwo Road",
  "Ibadan — Iyaganku",
  "Ibadan — Jericho",
  "Ibadan — Kolapo Ishola",
  "Ibadan — Lagelu",
  "Ibadan — Lekan Salami",
  "Ibadan — Mokola",
  "Ibadan — Monatan",
  "Ibadan — New Bodija",
  "Ibadan — Ojoo",
  "Ibadan — Oluyole",
  "Ibadan — Omi Adio",
  "Ibadan — Ring Road",
  "Ibadan — Sango",
  "Ibadan — Sanyo",
  "Ibadan — Secretariat Road",
  "Ibadan — Shasha",
  "Ibadan — Tipper Garage",
  "Ibadan — Dugbe",
  "Ibadan — Agege",
  "Ibadan — Akala",
  "Ibadan — Egbeda",
  "Ibadan — Ojo",
  "Ibadan — Ajibode",
  "Ibadan — Ologuneru",
  "Ibadan — Gate",
  "Ibadan — Gbagi",
  "Ibadan — Molete",
  "Ibadan — Orita Challenge",
  "Ibadan — Oke-Ado",
  "Ibadan — Oke Bola",
  "Ibadan — Padi",
  "Ibadan — Poly",
  "Ibadan — UI",
  "Ibadan — Ojoo",
  "Ibadan — Abebi",
  "Ibadan — Ojoo Road",
  "Ibadan — Yemetu",
  "Ibadan — Ejioku",
  "Oyo — Ogbomosho",
  "Oyo — Oyo Town",
  "Oyo — Iseyin",
  "Oyo — Saki",
  "Oyo — Igboho",
  "Oyo — Eruwa",
  "Oyo — Igbo-Ora",
  "Oyo — Kisi",

  // ========== KANO STATE ==========
  "Kano — Bompai",
  "Kano — Bompai Industrial",
  "Kano — Chalawa Industrial",
  "Kano — Dala",
  "Kano — Dambatta",
  "Kano — Fagge",
  "Kano — Gabasawa",
  "Kano — Gwale",
  "Kano — Hotoro",
  "Kano — Kano Municipal",
  "Kano — Kibiya",
  "Kano — Kiru",
  "Kano — Kumbotso",
  "Kano — Kunchi",
  "Kano — Madobi",
  "Kano — Makoda",
  "Kano — Nassarawa GRA",
  "Kano — Panshekara",
  "Kano — Rano",
  "Kano — Rijiyar Zaki",
  "Kano — Sabon Gari",
  "Kano — Sharada Industrial",
  "Kano — Tarauni",
  "Kano — Tofa",
  "Kano — Tudun Wada",
  "Kano — Ungogo",
  "Kano — Wudil",
  "Kano — Zaria Road",

  // ========== KADUNA STATE ==========
  "Kaduna — Badikko",
  "Kaduna — Barnawa",
  "Kaduna — GRA",
  "Kaduna — Gonin Gora",
  "Kaduna — Independence Way",
  "Kaduna — Kabala Costain",
  "Kaduna — Kabala West",
  "Kaduna — Kawo",
  "Kaduna — Malali",
  "Kaduna — Narayi",
  "Kaduna — Rigasa",
  "Kaduna — Sabo",
  "Kaduna — Sabon Tasha",
  "Kaduna — Television",
  "Kaduna — Tudun Wada",
  "Kaduna — Unguwan Dosa",
  "Kaduna — Unguwan Rimi",
  "Kaduna — Unguwan Sarki",
  "Zaria — GRA",
  "Zaria — Samaru",
  "Zaria — Tudun Wada",
  "Kaduna — Kafanchan",

  // ========== ENUGU STATE ==========
  "Enugu — Abakpa",
  "Enugu — Achara Layout",
  "Enugu — Agbani Road",
  "Enugu — Asata",
  "Enugu — Awkunanaw",
  "Enugu — Coal Camp",
  "Enugu — Emene",
  "Enugu — Gariki",
  "Enugu — GRA",
  "Enugu — Independence Layout",
  "Enugu — Maryland Layout",
  "Enugu — New Haven",
  "Enugu — Nike",
  "Enugu — Obiagu",
  "Enugu — Ogui",
  "Enugu — Presidential Road",
  "Enugu — Thinkers Corner",
  "Enugu — Trans Ekulu",
  "Enugu — Ugwuaji",
  "Enugu — Uwani",
  "Enugu — Ninth Mile",
  "Enugu — Agwu",
  "Enugu — Oji River",
  "Enugu — Udi",

  // ========== DELTA STATE ==========
  "Asaba — Cable Point",
  "Asaba — GRA",
  "Asaba — Infant Jesus",
  "Asaba — Ogbeogonogo",
  "Asaba — Okpanam Road",
  "Asaba — Summit",
  "Asaba — Umuezei",
  "Delta — Abraka",
  "Delta — Agbor",
  "Delta — Isoko",
  "Delta — Kwale",
  "Delta — Ogwashi-Ukwu",
  "Delta — Oleh",
  "Delta — Ozoro",
  "Delta — Sapele",
  "Delta — Ughelli",
  "Warri — Effurun",
  "Warri — Ekpan",
  "Warri — GRA",
  "Warri — Okpe",
  "Warri — Udu",
  "Warri — Uvwie",

  // ========== ANAMBRA STATE ==========
  "Awka — Amawbia",
  "Awka — GRA",
  "Awka — Nnewi",
  "Awka — Okpuno",
  "Awka — Unizik Junction",
  "Onitsha — Fegge",
  "Onitisha — GRA",
  "Onitsha — Inland Town",
  "Onitsha — Trans Nkisi",
  "Onitsha — Woliwo",
  "Anambra — Agulu",
  "Anambra — Ekwulobia",
  "Anambra — Ihiala",
  "Anambra — Nnewi",
  "Anambra — Oba",
  "Anambra — Ogidi",
  "Anambra — Orumba",
  "Anambra — Ozubulu",
  "Anambra — Ukpor",

  // ========== EDO STATE ==========
  "Benin City — Aduwawa",
  "Benin City — Avbiama",
  "Benin City — Ekosodin",
  "Benin City — Eyaen",
  "Benin City — GRA",
  "Benin City — Ikpoba Hill",
  "Benin City — New Benin",
  "Benin City — Ogida",
  "Benin City — Oliha",
  "Benin City — Oregbeni",
  "Benin City — Sapele Road",
  "Benin City — Ugbowo",
  "Benin City — Uselu",
  "Edo — Auchi",
  "Edo — Ekpoma",
  "Edo — Igarra",
  "Edo — Igueben",
  "Edo — Uromi",
  "Edo — Ubiaja",

  // ========== OGUN STATE ==========
  "Abeokuta — Camp",
  "Abeokuta — Elega",
  "Abeokuta — Ibara",
  "Abeokuta — Kuto",
  "Abeokuta — Lafenwa",
  "Abeokuta — Oke-Mosan",
  "Abeokuta — Onikolobo",
  "Abeokuta — Panseke",
  "Abeokuta — Sapon",
  "Ijebu-Ode — GRA",
  "Ijebu-Ode — Itoro",
  "Sagamu — GRA",
  "Sagamu — Ogijo",
  "Sagamu — Ikenne",
  "Ogun — Agbara",
  "Ogun — Ibafo",
  "Ogun — Ilaro",
  "Ogun — Mowe",
  "Ogun — Ofada",
  "Ogun — Ota",
  "Ogun — Owode",
  "Ogun — Sango Otta",

  // ========== ONDO STATE ==========
  "Akure — Alagbaka",
  "Akure — GRA",
  "Akure — Ijoka",
  "Akure — Ijomu",
  "Akure — Isikan",
  "Akure — Oba-Ile",
  "Akure — Oke-Aro",
  "Ondo — Idanre",
  "Ondo — Ikare",
  "Ondo — Okitipupa",
  "Ondo — Ondo Town",
  "Ondo — Ore",
  "Ondo — Owo",

  // ========== OSUN STATE ==========
  "Osogbo — Alekuwodo",
  "Osogbo — Ataoja",
  "Osogbo — GRA",
  "Osogbo — Igbona",
  "Osogbo — Oke-Baale",
  "Ile-Ife — GRA",
  "Ile-Ife — Moore",
  "Osun — Ede",
  "Osun — Ejigbo",
  "Osun — Ikire",
  "Osun — Ikirun",
  "Osun — Ilesa",
  "Osun — Iwo",

  // ========== EKITI STATE ==========
  "Ado-Ekiti — Basiri",
  "Ado-Ekiti — GRA",
  "Ado-Ekiti — Oke-Ila",
  "Ado-Ekiti — Oluyemi Kayode",
  "Ekiti — Efon-Alaye",
  "Ekiti — Ijero-Ekiti",
  "Ekiti — Ikere-Ekiti",
  "Ekiti — Emure-Ekiti",
  "Ekiti — Oye-Ekiti",

  // ========== KWARA STATE ==========
  "Ilorin — Adewole",
  "Ilorin — Asa Dam",
  "Ilorin — Challenge",
  "Ilorin — Fate",
  "Ilorin — Geri-Alimi",
  "Ilorin — GRA",
  "Ilorin — Kulende",
  "Ilorin — Oloje",
  "Ilorin — Sango",
  "Ilorin — Tanke",
  "Ilorin — Unity Road",
  "Kwara — Jebba",
  "Kwara — Lafiagi",
  "Kwara — Offa",
  "Kwara — Patigi",

  // ========== NIGER STATE ==========
  "Minna — Bosso",
  "Minna — Chanchaga",
  "Minna — GRA",
  "Minna — Kpakungu",
  "Minna — Maitumbi",
  "Minna — Tunga",
  "Niger — Bida",
  "Niger — Kontagora",
  "Niger — Lapai",
  "Niger — Suleja",
  "Niger — Agaie",

  // ========== KOGI STATE ==========
  "Lokoja — Felele",
  "Lokoja — Ganaja",
  "Lokoja — GRA",
  "Lokoja — Kabawa",
  "Lokoja — Zango",
  "Kogi — Ajaokuta",
  "Kogi — Ankpa",
  "Kogi — Idah",
  "Kogi — Kabba",
  "Kogi — Okene",

  // ========== BENUE STATE ==========
  "Makurdi — Ankpa Quarters",
  "Makurdi — GRA",
  "Makurdi — High Level",
  "Makurdi — North Bank",
  "Makurdi — Wurukum",
  "Benue — Gboko",
  "Benue — Katsina-Ala",
  "Benue — Otukpo",
  "Benue — Vandeikya",

  // ========== PLATEAU STATE ==========
  "Jos — Angwan Rogo",
  "Jos — Angwan Rukuba",
  "Jos — Bauchi Road",
  "Jos — Bukuru",
  "Jos — GRA",
  "Jos — Rayfield",
  "Jos — Tudun Wada",
  "Jos — Vom",
  "Plateau — Barkin Ladi",
  "Plateau — Bokkos",
  "Plateau — Mangu",
  "Plateau — Pankshin",
  "Plateau — Shendam",

  // ========== NASARAWA STATE ==========
  "Lafia — Central Market",
  "Lafia — Doma Road",
  "Lafia — GRA",
  "Nasarawa — Akwanga",
  "Nasarawa — Doma",
  "Nasarawa — Keffi",
  "Nasarawa — Nasarawa Town",
  "Nasarawa — Wamba",

  // ========== BAUCHI STATE ==========
  "Bauchi — Azare",
  "Bauchi — Dass",
  "Bauchi — Federal Low Cost",
  "Bauchi — Gombe Road",
  "Bauchi — GRA",
  "Bauchi — Maiduguri Road",
  "Bauchi — Makama",
  "Bauchi — Misau",
  "Bauchi — Wunti",

  // ========== GOMBE STATE ==========
  "Gombe — Billiri",
  "Gombe — Doma",
  "Gombe — GRA",
  "Gombe — Herwagana",
  "Gombe — Kaltungo",
  "Gombe — Nafada",
  "Gombe — Pantami",
  "Gombe — Tudun Wada",

  // ========== ADAMAWA STATE ==========
  "Yola — Doubeli",
  "Yola — GRA",
  "Yola — Jimeta",
  "Yola — Karewa",
  "Adamawa — Ganye",
  "Adamawa — Michika",
  "Adamawa — Mubi",
  "Adamawa — Numan",

  // ========== TARABA STATE ==========
  "Jalingo — GRA",
  "Jalingo — Yelwa",
  "Taraba — Bali",
  "Taraba — Gembu",
  "Taraba — Sardauna",
  "Taraba — Takum",
  "Taraba — Wukari",

  // ========== BORNO STATE ==========
  "Maiduguri — Bama Road",
  "Maiduguri — Bulumkutu",
  "Maiduguri — Gamboru Ngala",
  "Maiduguri — GRA",
  "Maiduguri — Kaleri",
  "Maiduguri — Pompomari",
  "Borno — Bama",
  "Borno — Biu",
  "Borno — Dikwa",
  "Borno — Monguno",

  // ========== YOBE STATE ==========
  "Damaturu — GRA",
  "Damaturu — Pompomari",
  "Yobe — Gashua",
  "Yobe — Geidam",
  "Yobe — Nguru",
  "Yobe — Potiskum",

  // ========== SOKOTO STATE ==========
  "Sokoto — Arkilla",
  "Sokoto — Gawon Nama",
  "Sokoto — GRA",
  "Sokoto — Kware",
  "Sokoto — Mabera",
  "Sokoto — Runjin Sambo",
  "Sokoto — Tambuwal",
  "Sokoto — Tudun Wada",
  "Sokoto — Wamakko",

  // ========== ZAMFARA STATE ==========
  "Gusau — GRA",
  "Gusau — Sabon Gari",
  "Zamfara — Anka",
  "Zamfara — Kaura Namoda",
  "Zamfara — Maradun",
  "Zamfara — Talata Mafara",

  // ========== KEBBI STATE ==========
  "Birnin Kebbi — Audi",
  "Birnin Kebbi — GRA",
  "Kebbi — Argungu",
  "Kebbi — Koko",
  "Kebbi — Yauri",
  "Kebbi — Zuru",

  // ========== JIGAWA STATE ==========
  "Dutse — Central Area",
  "Dutse — GRA",
  "Jigawa — Birnin Kudu",
  "Jigawa — Gumel",
  "Jigawa — Hadejia",
  "Jigawa — Kazaure",
  "Jigawa — Ringim",

  // ========== KATSINA STATE ==========
  "Katsina — Batagarawa",
  "Katsina — Daura",
  "Katsina — Funtua",
  "Katsina — GRA",
  "Katsina — Kofar Sauri",
  "Katsina — Malumfashi",
  "Katsina — Mani",
  "Katsina — Sabon Gari",

  // ========== CROSS RIVER STATE ==========
  "Calabar — 8 Miles",
  "Calabar — Atimbo",
  "Calabar — Diamond Hill",
  "Calabar — GRA",
  "Calabar — Lemna",
  "Calabar — Satellite Town",
  "Calabar — State Housing",
  "Cross River — Ikom",
  "Cross River — Obubra",
  "Cross River — Obudu",
  "Cross River — Ogoja",
  "Cross River — Akamkpa",

  // ========== AKWA IBOM STATE ==========
  "Uyo — Aka Road",
  "Uyo — Ewet Housing",
  "Uyo — GRA",
  "Uyo — Nung Ukana",
  "Uyo — Ring Road",
  "Uyo — Use Offot",
  "Uyo — Wellington Bassey Way",
  "Akwa Ibom — Abak",
  "Akwa Ibom — Eket",
  "Akwa Ibom — Ikot Abasi",
  "Akwa Ibom — Ikot Ekpene",
  "Akwa Ibom — Oron",

  // ========== IMO STATE ==========
  "Owerri — Aladinma",
  "Owerri — GRA",
  "Owerri — Housing Estate",
  "Owerri — Ikenegbu",
  "Owerri — New Owerri",
  "Owerri — Okigwe Road",
  "Owerri — Wetheral Road",
  "Imo — Mbaise",
  "Imo — Oguta",
  "Imo — Ohaji",
  "Imo — Okigwe",
  "Imo — Orlu",

  // ========== ABIA STATE ==========
  "Aba — Ariaria",
  "Aba — Cemetery Road",
  "Aba — Eziukwu",
  "Aba — GRA",
  "Aba — Ogbor Hill",
  "Aba — Osisioma",
  "Umuahia — GRA",
  "Umuahia — Ndiegoro",
  "Umuahia — Ubakala",
  "Abia — Arochukwu",
  "Abia — Isuikwuato",
  "Abia — Ohafia",

  // ========== EBONYI STATE ==========
  "Abakaliki — GRA",
  "Abakaliki — Kpirikpiri",
  "Abakaliki — Mile 50",
  "Abakaliki — Waterworks Road",
  "Ebonyi — Afikpo",
  "Ebonyi — Ezza",
  "Ebonyi — Ishielu",
  "Ebonyi — Onueke",

  // ========== BAYELSA STATE ==========
  "Yenagoa — Azikoro",
  "Yenagoa — Biogbolo",
  "Yenagoa — GRA",
  "Yenagoa — Kpansia",
  "Yenagoa — Onopa",
  "Yenagoa — Tombia",
  "Bayelsa — Brass",
  "Bayelsa — Ekeremor",
  "Bayelsa — Ogbia",
  "Bayelsa — Sagbama",
];

export const properties = [
  {
    id: 0,
    title: "The Meridian Penthouse",
    type: "apartment",
    status: "sale",
    location: "Lagos — Victoria Island",
    beds: 4,
    baths: 4,
    sqft: 3200,
    price: 450000000,
    priceLabel: "₦450,000,000",
    color: "linear-gradient(135deg, #1a2d3a, #2d4a5a)",
    desc: "An exceptional penthouse residence offering panoramic views of Lagos lagoon. Floor-to-ceiling windows, private rooftop terrace, and premium finishes throughout.",
    features: [
      "Rooftop Terrace",
      "Lagoon View",
      "Smart Home",
      "Private Pool",
      "24/7 Security",
      "Concierge",
    ],
    featured: true,
    newest: true,
  },
  {
    id: 1,
    title: "Asokoro Garden Villa",
    type: "house",
    status: "sale",
    location: "Abuja — Asokoro",
    beds: 5,
    baths: 5,
    sqft: 4800,
    price: 380000000,
    priceLabel: "₦380,000,000",
    color: "linear-gradient(135deg, #1a2d1f, #2d4a35)",
    desc: "A stunning contemporary villa set within manicured gardens in one of Abuja's most prestigious addresses. Generous living spaces, private pool and dedicated staff quarters.",
    features: [
      "Private Pool",
      "Staff Quarters",
      "Garden",
      "CCTV",
      "Generator",
      "BQ",
    ],
    featured: true,
    newest: false,
  },
  {
    id: 2,
    title: "Lekki Phase 1 Duplex",
    type: "duplex",
    status: "sale",
    location: "Lagos — Lekki Phase 1",
    beds: 4,
    baths: 3,
    sqft: 2800,
    price: 180000000,
    priceLabel: "₦180,000,000",
    color: "linear-gradient(135deg, #2d1a3a, #4a2d5a)",
    desc: "A well-appointed duplex in the heart of Lekki Phase 1. Ideal for families, featuring a large open-plan living area, modern kitchen, and a private garden.",
    features: [
      "4 Car Park",
      "Private Garden",
      "Fitted Kitchen",
      "Security",
      "Inverter",
    ],
    featured: true,
    newest: false,
  },
  {
    id: 3,
    title: "Ikoyi Modern Apartment",
    type: "apartment",
    status: "rent",
    location: "Lagos — Ikoyi",
    beds: 3,
    baths: 3,
    sqft: 1800,
    price: 12000000,
    priceLabel: "₦12,000,000/yr",
    color: "linear-gradient(135deg, #1a1a2d, #2d2d4a)",
    desc: "A refined 3-bedroom apartment in the heart of Ikoyi, offering sophisticated urban living with stunning views and access to premium building amenities.",
    features: ["Gym", "Pool", "Doorman", "Parking", "Backup Power"],
    featured: false,
    newest: true,
  },
  {
    id: 4,
    title: "Maitama Executive Home",
    type: "house",
    status: "sale",
    location: "Abuja — Maitama",
    beds: 6,
    baths: 6,
    sqft: 5500,
    price: 620000000,
    priceLabel: "₦620,000,000",
    color: "linear-gradient(135deg, #2d2a1a, #4a441f)",
    desc: "A magnificent executive residence in Maitama. Sprawling grounds, cinema room, wine cellar, and an entertainer's dream outdoor space.",
    features: [
      "Cinema Room",
      "Wine Cellar",
      "Outdoor Kitchen",
      "Tennis Court",
      "Pool",
      "6 Car Garage",
    ],
    featured: false,
    newest: false,
  },
  {
    id: 5,
    title: "VI Commercial Office Space",
    type: "commercial",
    status: "rent",
    location: "Lagos — Victoria Island",
    beds: 0,
    baths: 4,
    sqft: 3600,
    price: 35000000,
    priceLabel: "₦35,000,000/yr",
    color: "linear-gradient(135deg, #1a2a2a, #2d4a4a)",
    desc: "Grade-A open-plan office space spanning a full floor in one of VI's most prestigious commercial buildings. Ideal for corporate headquarters.",
    features: [
      "Open Plan",
      "Meeting Rooms",
      "Reception",
      "Server Room",
      "Generator",
      "Parking",
    ],
    featured: false,
    newest: true,
  },
  {
    id: 6,
    title: "Lekki Shortlet Studio",
    type: "apartment",
    status: "shortlet",
    location: "Lagos — Lekki Phase 2",
    beds: 1,
    baths: 1,
    sqft: 650,
    price: 85000,
    priceLabel: "₦85,000/night",
    color: "linear-gradient(135deg, #2d1a1a, #4a2d2d)",
    desc: "A beautifully furnished studio apartment available for short stays. Fully equipped kitchen, high-speed WiFi, smart TV and weekly housekeeping included.",
    features: [
      "Fully Furnished",
      "WiFi",
      "Smart TV",
      "Kitchen",
      "Weekly Clean",
    ],
    featured: false,
    newest: true,
  },
  {
    id: 7,
    title: "Ibadan Estate Bungalow",
    type: "house",
    status: "sale",
    location: "Ibadan — GRA",
    beds: 3,
    baths: 2,
    sqft: 1600,
    price: 45000000,
    priceLabel: "₦45,000,000",
    color: "linear-gradient(135deg, #1f2d1a, #354a2d)",
    desc: "A charming 3-bedroom bungalow in the prestigious GRA area of Ibadan. Well-maintained with a large compound, perfect for a growing family.",
    features: [
      "Large Compound",
      "Security",
      "Borehole",
      "Generator",
      "Parking",
    ],
    featured: false,
    newest: false,
  },
  {
    id: 8,
    title: "Wuse 2 Luxury Apartment",
    type: "apartment",
    status: "rent",
    location: "Abuja — Wuse 2",
    beds: 2,
    baths: 2,
    sqft: 1200,
    price: 8000000,
    priceLabel: "₦8,000,000/yr",
    color: "linear-gradient(135deg, #1a2d2a, #2d4a45)",
    desc: "A tastefully finished 2-bedroom apartment in the vibrant Wuse 2 district. Walking distance from top restaurants, banks, and the major diplomatic zones.",
    features: ["Gym Access", "Pool", "Security", "Generator", "Parking"],
    featured: false,
    newest: false,
  },
  {
    id: 9,
    title: "Port Harcourt GRA Duplex",
    type: "duplex",
    status: "sale",
    location: "Port Harcourt — GRA Phase 1",
    beds: 4,
    baths: 4,
    sqft: 3000,
    price: 130000000,
    priceLabel: "₦130,000,000",
    color: "linear-gradient(135deg, #2a1a2d, #4a2d50)",
    desc: "A solidly built 4-bedroom duplex in the heart of Port Harcourt GRA. Excellent access to the oil & gas business district. Strong investment potential.",
    features: ["BQ", "Parking", "Security", "Inverter", "Water Treatment"],
    featured: false,
    newest: false,
  },
  {
    id: 10,
    title: "Lekki Smart Apartment",
    type: "apartment",
    status: "sale",
    location: "Lagos — Lekki Phase 1",
    beds: 2,
    baths: 2,
    sqft: 1100,
    price: 75000000,
    priceLabel: "₦75,000,000",
    color: "linear-gradient(135deg, #1a1f2d, #2d354a)",
    desc: "A beautifully finished smart apartment in a brand-new development. Features automated lighting, climate control, and a concierge app for all building services.",
    features: ["Smart Home", "Concierge App", "Rooftop Lounge", "Gym", "Pool"],
    featured: false,
    newest: true,
  },
  {
    id: 11,
    title: "Ibadan Commercial Plaza",
    type: "commercial",
    status: "sale",
    location: "Ibadan — Bodija",
    beds: 0,
    baths: 6,
    sqft: 8000,
    price: 250000000,
    priceLabel: "₦250,000,000",
    color: "linear-gradient(135deg, #2d2a1a, #504a2d)",
    desc: "A fully tenanted commercial plaza in Ibadan's busiest commercial corridor. Multiple retail units with strong existing rental income.",
    features: ["8 Retail Units", "Car Park", "Security", "Generator", "CCTV"],
    featured: false,
    newest: false,
  },
];
